import Head from 'next/head';
import Image from 'next/image';
import Portfolio from '../public/images/portfolio-1.png';
import React, { useState } from 'react';

export default function Home() {
	const [showMenu, setShowMenu] = useState(true);

	let menu;

	if (showMenu) {
		menu = (
			<div className="fixed bg-green-450 text-2xl flex flex-col py-4 justify-center items-center inset-0 ">
				<a className="link" href="">
					Portfilio
				</a>
				<a className="link" href="">
					About
				</a>
				<a className="link" href="">
					Contact me
				</a>
			</div>
		);
	}
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>

				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<header className="bg-green-450 p-4 w-full ">
					<div className=" flex mx-auto w-full justify-between items-center text-white">
						<div className="text-4xl">SteffOverflow</div>
						<div className="hidden laptop:block">
							<a className="link" href="">
								Portfilio
							</a>
							<a className="link" href="">
								About
							</a>
							<a className="link" href="">
								Contact me
							</a>
						</div>

						{menu}

						<button
							onClick={() => setShowMenu(!showMenu)}
							className="fixed bottom-4 right-4 rounded-full px-4 py-6 z-50 laptop:hidden bg-pink-500 "
						>
							Menu
						</button>
					</div>
				</header>
				<main>
					<div className="container mx-auto flex flex-row justify-between items-center py-32 bg-[url('/images/hero-pattern.png')] bg-cover bg-no-repeat bg-center ">
						<div className="flex flex-col">
							<h1 className="">I build awesome experiences.</h1>
							<p className="mb-10">
								I am a webdeveloper | UI & UX designer
							</p>
							<a
								className="bg-pink-500 cursor-pointer text-white px-4 py-2 hover:bg-pink-800 rounded w-max"
								href=""
							>
								Check out my work!
							</a>
						</div>
						<div>
							<Image
								src="/images/header-illustration.svg"
								width={500}
								height={500}
								className=""
								alt=""
							/>
						</div>
					</div>

					<div className="container mx-auto my-24 ">
						<h2>Portfolio</h2>

						<p className=" ">
							Lorem, ipsum dolor sit amet consectetur adipisicing
							elit. Voluptatum quaerat eum fuga ex sit, amet
							officia sapiente, in nam fugiat animi unde beatae,
							maiores molestiae. Ducimus amet adipisci magnam
							voluptas modi est deleniti mollitia voluptatibus
							expedita! Id consectetur ipsam iure sunt debitis,
							facere, dolorem optio, dolorum quasi temporibus
							distinctio velit pariatur harum quaerat sit ducimus
							officiis delectus quod voluptatem. Quos, at? Tempora
							consectetur atque ducimus, reiciendis aspernatur,
							rem numquam ipsam voluptatem id cupiditate mollitia
							quia totam, nam eius odio. Neque, quae illum ducimus
							sed ex numquam dignissimos cupiditate error officiis
							ad veritatis reiciendis repellendus dicta? Harum
							delectus enim deleniti ratione impedit pariatur
							expedita laboriosam, assumenda nostrum sunt fugit
							eius ipsa consequuntur facilis molestiae
							perspiciatis? Perspiciatis nam libero autem
							repellendus nostrum suscipit, nobis eaque illo quod,
							consequuntur nemo natus quidem exercitationem beatae
							nisi. Magni atque itaque numquam culpa! Dolores,
							officiis! Ratione animi in odit quod. Eos velit quod
							assumenda officia expedita?
						</p>
						<div className="grid grid-cols-2 gap-8 my-8 ">
							<div className="  col-span-1 bg-[url('/images/portfolio-work-background.svg')]  bg-cover bg-no-repeat bg-center  round-lg p-3">
								<Image
									src={Portfolio}
									alt="portfolio image"
									height={283}
									width={496}
									layout="responsive"
									className="rounded-lg "
								/>
							</div>
							<div className=" col-span-1 bg-[url('/images/portfolio-work-background.svg')] bg-cover bg-no-repeat bg-center  round-lg p-3">
								<Image
									src={Portfolio}
									alt="portfolio image"
									height={283}
									width={496}
									layout="responsive"
									className="rounded-lg "
								/>
							</div>
						</div>
					</div>
					<div className="container mx-auto  my-24 bg-[url('/images/about-pattern.png')] bg-cover bg-no-repeat bg-center">
						<h2>About</h2>
						<div className="flex gap-6 items-center mx-[65px]">
							<div className="flex-1 bg-[url('/images/portfolio-pattern.svg')] bg-cover bg-no-repeat bg-center  round-lg p-3">
								<Image
									src={Portfolio}
									alt="portfolio image"
									height={283}
									width={496}
									layout="responsive"
									className="rounded-lg "
								/>
							</div>
							<p className="flex-1 ">
								Lorem, ipsum dolor sit amet consectetur
								adipisicing elit. Voluptatum quaerat eum fuga ex
								sit, amet officia sapiente, in nam fugiat animi
								unde beatae, maiores molestiae. Ducimus amet
								adipisci magnam voluptas modi est deleniti
								mollitia voluptatibus expedita! Id consectetur
								ipsam iure sunt debitis, facere, dolorem optio,
								dolorum quasi temporibus distinctio velit
								pariatur harum quaerat sit ducimus officiis
								delectus quod voluptatem. Quos, at? Tempora
								consectetur atque ducimus, reiciendis
								aspernatur, rem numquam ipsam voluptatem id
								cupiditate mollitia quia totam, nam eius odio.
								Neque, quae illum ducimus sed ex numquam
								dignissimos cupiditate error officiis ad
								veritatis reiciendis repellendus dicta?
							</p>
						</div>
					</div>
					<div className="container mx-auto bg-[url('/images/form-pattern.png')] bg-cover bg-no-repeat bg-center">
						<h2>Contact Me</h2>
						<p>
							Lorem, ipsum dolor sit amet consectetur adipisicing
							elit. Voluptatum quaerat eum fuga ex sit, amet
							officia sapiente, in nam fugiat animi unde beatae,
							maiores molestiae. Ducimus amet adipisci magnam
							voluptas modi est deleniti mollitia voluptatibus
							expedita! Id consectetur ipsam iure sunt debitis,
							facere, dolorem optio, dolorum quasi temporibus
							distinctio velit pariatur harum quaerat sit ducimus
							officiis delectus quod voluptatem. Quos, at?
						</p>
						<form
							method="POST"
							className="grid grid-cols-2 gap-8 mt-8 laptop:mt-32"
						>
							<label
								html="email"
								className="col-span-2 laptop:col-span-1 "
							>
								Your Email:
								<input
									name="email"
									className="border-2 border-gray-100 w-full py-4"
								/>
							</label>
							<label
								html="honeypot"
								className="hidden laptop:col-span-1"
							>
								<input
									type="hidden"
									name="honeypot"
									className="border-2 border-gray-100 w-full py-4"
								/>
							</label>
							<label
								html="firstname"
								className="col-span-2 laptop:col-span-1"
							>
								Your First name:
								<input
									name="firstname"
									className="border-2 border-gray-100 w-full py-4"
								/>
							</label>
							<label
								html="lastname"
								className="col-span-2 laptop:col-span-1"
							>
								Your Last name:
								<input
									name="lastname"
									className="border-2 border-gray-100 w-full py-4"
								/>
							</label>

							<label html="message" className="col-span-2">
								Your Message:
								<textarea
									name="message"
									className="border-2 border-gray-100 w-full"
								></textarea>
							</label>
							<button
								type="submit"
								className="col-span-2 button p-6 mb-12 bg-pink-500  rounded-lg text-large text-white "
							>
								Contact me
							</button>
						</form>
					</div>
				</main>
			</div>
		</>
	);
}
